# ================================
# BASIC SITE SETTINGS
# ================================
locale                   : "en-US"
site_theme               : "default"
title                    : "Pankaj Yadav | Data Generation & Probabilistic AI Research"
title_separator          : "-"
name                     : &name "Pankaj Yadav"
description              : &description "PhD researcher working on probabilistic modeling and AI-based data generation. My work bridges statistical inference and deep generative models to improve data efficiency, interpretability, and robustness in healthcare, solar, finance, and sports science data."
url                      : "https://pankajyadav.github.io"
baseurl                  : ""
repository               : "pankajyadav/pankajyadav.github.io"

# ================================
# AUTHOR DETAILS (SIDEBAR)
# ================================
author:
  avatar           : "profile.png"   # Upload your photo in /images/ as profile.png
  name             : "Pankaj Yadav"
  pronouns         : "he/him"
  bio              : "PhD researcher working on probabilistic modeling and AI-based data generation. My work spans healthcare, solar energy, finance, and sports science—focusing on interpretable and efficient generative models."
  location         : "India"
  employer         : "PhD Researcher"
  uri              : "https://pankajyadav.github.io"
  email            : "yadav.58@iitj.ac.in"

  # Academic Profiles
  googlescholar    : "https://scholar.google.co.in/citations?hl=en&user=ejZNgHgAAAAJ"
  orcid            : "https://orcid.org/0009-0009-1437-5659?lang=en"
  github           : "pankajyadav"
  linkedin         : "https://www.linkedin.com/in/pankaj-yadav-867a40200?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app"

# ================================
# PUBLICATION CATEGORIES
# ================================
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'

# ================================
# SITE SETTINGS
# ================================
teaser                   :
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false
comments:
  provider               : false

atom_feed:
  hide                   : false
  path                   : 

# ================================
# SEO & SOCIAL
# ================================
social:
  type                   : "Person"
  name                   : "Pankaj Yadav"
  links:
    - "https://scholar.google.com/"
    - "https://linkedin.com/in/pankajyadav"
    - "https://github.com/pankajyadav"
    - "https://orcid.org/"

# ================================
# ANALYTICS (OPTIONAL)
# ================================
analytics:
  provider               : false

# ================================
# COLLECTIONS
# ================================
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# ================================
# MARKDOWN SETTINGS
# ================================
markdown: kramdown
highlighter: rouge
encoding: "utf-8"
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  entity_output: as_char

# ================================
# OUTPUT SETTINGS
# ================================
permalink: /:categories/:title/
timezone: Asia/Kolkata

# ================================
# PLUGINS
# ================================
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-paginate
  - jekyll-redirect-from

# ================================
# COMPRESS HTML
# ================================
compress_html:
  clippings: all
  ignore:
    envs: development
